fix: add missing msg type when parse from event
cosmos/relayer pull request #1196
Opened 2023-05-18 01:34 UTC by mmsqe

EventTypeChannelClosed 
EventTypeUpgradeChain 
EventTypeUpgradeClientProposal

2023-05-18 02:48 UTC, agouin commented
These new events will now be added to the cache, but nothing will be done with them after that.

`EventTypeChannelClosed` seems like a good one to handle to mark the channel closed in addition to the channel close confirm here https://github.com/cosmos/relayer/blob/45f478b597d09eff8a1b6d6327a65628f44a9747/relayer/chains/cosmos/message_handlers.go#L90

It's not clear to me why the relayer would need to care about `EventTypeUpgradeChain` or `EventTypeUpgradeClientProposal`. Can you expand on that?

2023-05-18 03:11 UTC, mmsqe commented
> It's not clear to me why the relayer would need to care about `EventTypeUpgradeChain` or `EventTypeUpgradeClientProposal`. Can you expand on that?

I thought these two client [events](https://github.com/cosmos/ibc-go/blob/v7.0.0/modules/core/02-client/types/events.go#L29-L30) was missing when upgrade from ibc-go v6 to v7

2023-10-12 18:07 UTC, jtieri requested changes
These changes look good to me, always nice to remove some duplicated code.

My only nitpick would be can we rename `utils.go` to something like `parsing.go`, `event_parser.go` or something along those lines?

2023-10-17 18:18 UTC, jtieri approved these changes

2023-10-17 18:18 UTC, merged