faddat/upgrade go
cosmos/relayer pull request #1279
Opened 2023-09-01 17:59 UTC by faddat

This PR upgrades the go relayer to go v1.21 in advance of upgrading to sdk 50.  It is meant to reduce the size of a PR that fully upgrades to 50.

- upgrade ci to go 1.21
- upgrade to go1.21

2023-09-03 05:14 UTC, faddat commented
is "TESTING - interchaintest / scenarios (pull_request) Failing after 11m" 

known to be flaky at all?  I figure this out to be good to go

2023-09-06 23:05 UTC, jtieri commented
> is "TESTING - interchaintest / scenarios (pull_request) Failing after 11m"
> 
> known to be flaky at all? I figure this out to be good to go

yes unfortunately our self hosted runner encounters oom errors. we have been discussing moving over to GitHub's hosted runners and making sure that each test case runs in its own job to avoid this issue.

2023-09-06 23:13 UTC, jtieri requested changes
just the comment regarding the Go version being referenced in the workflow files then this should be good to merge, thanks!

2023-09-06 23:13 UTC, jtieri commented on .github/workflows/build.yml
>        - name: Set up Go 1.20
can you also adjust the name to accurately reference the version of Go that is being used? better yet we could change this line to simply be `Setting up Go` that way we don't have to keep making changes every time we update the Go version being used.

2023-09-06 23:13 UTC, jtieri commented on .github/workflows/interchaintest.yml
>        - name: Set up Go 1.20
same as my last comment, maybe we quit referencing a specific Go version in the names that way we don't need to keep making changes every time we update the Go version.

2023-09-12 17:46 UTC, jtieri approved these changes

2023-09-12 18:16 UTC, merged