fix: add os.IsExist check for loadConfigFile error
cosmos/relayer pull request #1325
Opened 2023-11-09 03:26 UTC by mmsqe

2023-11-09 03:27 UTC, mmsqe commented on CHANGELOG.md
> +* [\#](https://github.com/cosmos/relayer/pull/) Ignore only file not exist error when loadConfigFile.
```suggestion
* [\#1325](https://github.com/cosmos/relayer/pull/1325) Ignore only file not exist error when loadConfigFile.
```

2023-11-09 20:48 UTC, jtieri requested changes

2023-11-09 20:48 UTC, jtieri commented on cmd/appstate.go
> +		if os.IsExist(err) {
small nit but the [Go docs](https://pkg.go.dev/os#IsExist) for `IsExists` states, "This function predates errors.Is. It only supports errors returned by the os package. New code should use errors.Is(err, fs.ErrExist)."

Could we possibly swap the `IsExists` call out for `errors.Is`?

2023-11-10 01:54 UTC, jtieri approved these changes
grazie!

2023-11-10 01:55 UTC, merged