Allow pathEnd version string to be specified in the config file
cosmos/relayer pull request #269
Opened 2020-06-01 16:49 UTC by michaelfig

Default, as before, to `"ics20-1"`, but this allows non-transfer ports to be relayed without much difficulty.

2020-06-29 12:00 UTC, colin-axner requested changes
LGTM besides the adding in the version to the `PathEnd` constructor

2020-06-29 12:00 UTC, colin-axner commented on relayer/path.go
> +func GenPath(srcChainID, dstChainID, srcPortID, dstPortID, order string, version string) *Path {
version var needs to be set in the `PathEnd` structs

2020-06-29 12:00 UTC, colin-axner commented on relayer/path.go
> +		return fmt.Errorf("Source must specify a version")
```suggestion
		return fmt.Errorf("source must specify a version")
```

2020-06-30 08:34 UTC, colin-axner approved these changes
Nice work :+1:

2020-07-14 10:24 UTC, fedekunze approved these changes

2020-07-14 10:24 UTC, merged