Implement bottom up validation
cosmos/relayer pull request #398
Opened 2021-01-29 11:31 UTC by akhilkumarpilli

Fixes: #345

2021-01-30 06:57 UTC, anilCSE requested changes

2021-01-30 06:57 UTC, anilCSE commented on cmd/config.go
> +// ValidatePathEnd allow validates provided pathend and returns error for invalid identifiers
```suggestion
// ValidatePathEnd validates provided pathend and returns error for invalid identifiers
```

2021-01-30 06:57 UTC, anilCSE commented on cmd/config.go
> +	}
This is duplicted in multiple places. May be better to change `ValidateClient` as `ValidateClient(chain, height, pathEnd)` . Also for `ValidateConnection` and `ValidateChannel`

2021-02-02 11:12 UTC, colin-axner approved these changes
LGTM, great work!

2021-02-02 12:36 UTC, anilCSE reviewed
lgtm, just small nits

2021-02-02 12:36 UTC, anilCSE commented on cmd/config.go
> +	}
Let's re-order this check
```suggestion
	if p.Src.Version == "" {
		return fmt.Errorf("source must specify a version")
	}
	if err = c.ValidatePathEnd(p.Src); err != nil {
		return err
	}
```

2021-02-02 12:36 UTC, anilCSE commented on cmd/config.go
> +	}
I think if the `ClientID` is nil, there's no point in validating connection or channel details. We can just return `err` if the ClientID is nil and connectionID is not nil. Similarly for ChannelID

```suggestion
	if pe.ClientID != "" {
		if err := c.ValidateClient(chain, height, pe); err != nil {
			return err
		}
		
		if pe.ConnectionID != "" {
		      if err := c.ValidateConnection(chain, height, pe); err != nil {
			      return err
		      }
		      
		      if pe.ChannelID != "" {
		            if err := c.ValidateChannel(chain, height, pe); err != nil {
			            return err
		            }
	            }
	      }
	}
	
	if pe.ClientID == "" && pe.ConnectionID != "" {
	    return fmt.Errorf("ClientID is not conifgured for the connection: %s", pe.ConnectionID)
	}
```

2021-02-02 13:55 UTC, anilCSE approved these changes

2021-02-02 13:56 UTC, merged