create client for substrate chains
cosmos/relayer pull request #946
Opened 2022-08-24 16:57 UTC by oshorefueled

This PR implements the required provider and query methods to create light clients across substrate and cosmos chains.

2022-10-26 18:28 UTC, jtieri requested changes
Just a few nits but otherwise this looks good

2022-10-26 18:28 UTC, jtieri commented on dev-env-sub
> +#!/bin/bash -e
Can we move this file into the directory with the other scripts/testing stuff? `./relayer/examples/demo/`

2022-10-26 18:28 UTC, jtieri commented on relayer/chains/substrate/key_test.go
> +	var provider = substrate.SubstrateProvider{}
`provider := substrate.SubstrateProvider{}` is slightly less verbose and achieves the same thing

2022-10-26 18:28 UTC, jtieri commented on relayer/chains/substrate/key_test.go
> +	var err error
It looks like this variable declaration could be removed

2022-10-26 18:28 UTC, jtieri commented on relayer/chains/substrate/query.go
> +	var relayChainHeight uint64
I don't see a reason why this variable needs to be declared before initialization down on L521

2022-10-26 18:28 UTC, jtieri commented on relayer/chains/substrate/query.go
> +	sp.LatestQueriedRelayChainHeight = 0
Why does this need to be reset after querying for an IBC header?

2022-10-26 18:28 UTC, jtieri commented on relayer/provider/matcher.go
> +		fmt.Printf("\nquery ibc header %v \n \n", existingClientState.GetLatestHeight().GetRevisionHeight())
Looks like some debug output that may need to be removed.

2022-10-26 18:28 UTC, jtieri commented on relayer/provider/matcher.go
> +			fmt.Printf("error quering header at height %v \n \n", existingClientState.GetLatestHeight().GetRevisionHeight())
Looks like some debug output that may need to be removed.

2022-10-26 18:28 UTC, jtieri commented on relayer/provider/matcher.go
> +			return "", fmt.Errorf("got type(%T) expected type(*tmclient.ConsensusState)", exportedConsState)
This should be `got type(%T) expected type(*beefyclienttypes.ConsensusState)`

2022-10-26 18:28 UTC, jtieri commented on relayer/provider/matcher.go
> +			return "", fmt.Errorf("got type(%T) expected type(*tmclient.ConsensusState)", consensusState)
This should be `got type(%T) expected type(*beefyclienttypes.ConsensusState)`

2022-10-27 21:21 UTC, oshorefueled commented on relayer/chains/substrate/query.go
> +	sp.LatestQueriedRelayChainHeight = 0
The reason for resetting the variable is to make sure that QueryLatestHeight is called before calling QueryIBCHeader. When QueryHeaderAtHeight is called in the relayer, the returned height from QueryLatestHeight is passed to the method as the height argument. In the substrate provider, calling QueryLatestHeight returns the latest finalized parachain height. However, to fetch the header, we need to query the relaychain, only problem is there's no way to fetch the header from the relaychain using the para height. So, we cache the latest finalized relaychain height when QueryLatestHeight is called and reset it when the QueryHeaderAtHeight is called. That way, we make sure we're using the latest finalized relaychain height when QueryHeaderAtHeight is called.

2022-11-01 19:05 UTC, jtieri approved these changes

2022-11-01 19:05 UTC, merged